
name: Node.js Test Builder CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: false
      - name: Install dependencies
        run: pnpm i --no-optional
      - name: Build project
        run: |
          npm run bundle
          zip -r nx-core-bundle-${{ runner.os }}.zip out/
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 4.4
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
      - name: Test Bundle Server
        run: |
          bash scripts/workflow/test-server.sh
      - name: Upload Linux Bundle
        uses: actions/upload-artifact@v3
        with:
          path: ./nx-core-bundle-${{ runner.os }}.zip
          name: nx-core-bundle-${{ runner.os }}.zip

          


  build_other_platform:
    name: Build Other Platform
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
            
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Build project
        run: |
          pnpm run bundle
          zip -r nx-core-bundle-${{ runner.os }}.zip out/
      
      - name: Upload Bundle
        uses: actions/upload-artifact@v3
        with:
          path: ./nx-core-bundle-${{ runner.os }}.zip
          name: nx-core-bundle-${{ runner.os }}.zip
