
name: Node.js Test Builder CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: false
      - name: Install dependencies
        run: pnpm i --no-optional
      - name: Build project
        run: |
          npm run bundle
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
      - name: Test Bundle Server
        run: |
          bash scripts/workflow/test-server.sh
      - name: Bundle Package
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: out/index.js

      - name: Install Pkg
        run: |
          npm install -g pkg
      
      - name: Cache Pkg binaries
        uses: actions/cache@v3
        env:
          cache-name: cache-pkg-binaries
        with:
          path: ~/.pkg-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build Pkg
        run: |
          pkg .
      
      - name: Cache Pkg binaries
        uses: actions/cache@v3
        env:
          cache-name: cache-pkg-binaries
        with:
          path: ~/.pkg-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Zip Pkg
        run: |
          
          zip -r nx-core-node16-linux.zip ./out/core-linux
          zip -r nx-core-node16-macos.zip ./out/core-macos
          zip -r nx-core-node16-win.zip ./out/core-win.exe

      - name: Upload macOS Pkg Asset
        uses: actions/upload-artifact@v3
        with:
          path: ./nx-core-node16-macos.zip
          name: nx-core-node16-macos.zip

      - name: Upload Linux Pkg Asset
        uses: actions/upload-artifact@v3
        with:
          path: ./nx-core-node16-linux.zip
          name: nx-core-node16-linux.zip

      - name: Upload Windows Pkg Asset
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./nx-core-node16-win.zip
          name: nx-core-node16-win.zip
          


