name: Lint
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.x
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install Dependencies
        run: |
          pnpm i --no-optional
      - name: Run lint
        run: |
          pnpm prettier --ignore-path ./.prettierignore --write **/*.{ts,yml,md}
          pnpm eslint --cache --fix .
      - name: Commit files
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "style: lint"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
        with:
          branch: ${{ github.head_ref }}
